  version: '3.1'
  services:
      database:
        image: postgres
        environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: logistics
        volumes:
          - ./postgres_data:/var/lib/postgresql/data/
        ports:
          - 5433:5432

